I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/charlie.rpy", line 2, in script
    jump prologue_2
ScriptError: could not find label 'prologue_2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/charlie.rpy", line 2, in script
    jump prologue_2
  File "C:\Users\krist\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\krist\Downloads\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'prologue_2'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Holidays in Harkmall 1.0
Tue Dec 13 21:28:57 2022
